Writable:
  LogLevel: DEBUG
Service:
  Host: "localhost"
  Port: 59911 # Device service are assigned the 599xx range
  StartupMsg: device demo started

MessageBus:
  Optional:
    ClientId: device-demo

# Example overriding of Common Config settings
Device:
  AsyncBufferSize: 1
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: ./res/profiles
  DevicesDir: ./res/devices
